
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: pubg-deploy
    env: lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pubg-app
  template:
    metadata:
      labels:
        app: pubg-app
        env: lab
        tier: frontend
        version: v1-ac
    spec:
      containers:
        - name: pubg-cont
          image: dockerhub7890/nandu123:6
          ports:
            - containerPort: 80
