---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: pubg-deploy
    env: lab

spec:
  selector:
    matchLabels:
      app: pubg-app
    
  replicas: 2
  template:
    metadata:
      name: pubg-app-pod
      labels: 
        app: pubg-app
        env: lab
        tier: frontend
        version: v1-ac

    spec:
      containers:
        - name: pubg-cont
          image: dockerhub7890/nandu123:fbapp
          
