apiVersion: v1
kind: Service
metadata:
  name: pubg-lb-svc
  labels:
    app: pubg-app
spec:
  type: LoadBalancer
  ports:
    - port: 80          # browser access port
      targetPort: 8080    # nginx container port
      protocol: TCP
  selector:
    app: pubg-app
